### ISSUE TITLE
Publish via Dockerhub

### ISSUE THREAD

**Issue by richardcase** [weaveworks/release-note-action#2]
Change the publishing of the action by doing the following:

- On tagging a release build the Actions container and push to https://hub.docker.com/repository/docker/weaveworks/release-note-action
- Ensure that the tag it DockerHub matches the tag in the actions.yaml. For example change the run to something like this:

```yaml
runs:
  using: 'docker'
  image: 'docker://weaveworks/release-note-action:v0.1.0'
```
